// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import { ANTHROPIC_CLASSIFIER_MODELS, ANTHROPIC_IMAGE_MODELS, ANTHROPIC_MODELS } from "./providers/anthropic.models.ts";
import { HUGGINGFACE_CLASSIFIER_MODELS, HUGGINGFACE_IMAGE_MODELS, HUGGINGFACE_MODELS } from "./providers/huggingface.models.ts";
import { OPENROUTER_CLASSIFIER_MODELS, OPENROUTER_IMAGE_MODELS, OPENROUTER_MODELS } from "./providers/openrouter.models.ts";

export const MODELS: {
	readonly "anthropic": typeof ANTHROPIC_MODELS;
	readonly "huggingface": typeof HUGGINGFACE_MODELS;
	readonly "openrouter": typeof OPENROUTER_MODELS;
} = {
	"anthropic": ANTHROPIC_MODELS,
	"huggingface": HUGGINGFACE_MODELS,
	"openrouter": OPENROUTER_MODELS,
};

export const IMAGE_MODELS: {
	readonly "anthropic": typeof ANTHROPIC_IMAGE_MODELS;
	readonly "huggingface": typeof HUGGINGFACE_IMAGE_MODELS;
	readonly "openrouter": typeof OPENROUTER_IMAGE_MODELS;
} = {
	"anthropic": ANTHROPIC_IMAGE_MODELS,
	"huggingface": HUGGINGFACE_IMAGE_MODELS,
	"openrouter": OPENROUTER_IMAGE_MODELS,
};

export const CLASSIFIER_MODELS: {
	readonly "anthropic": typeof ANTHROPIC_CLASSIFIER_MODELS;
	readonly "huggingface": typeof HUGGINGFACE_CLASSIFIER_MODELS;
	readonly "openrouter": typeof OPENROUTER_CLASSIFIER_MODELS;
} = {
	"anthropic": ANTHROPIC_CLASSIFIER_MODELS,
	"huggingface": HUGGINGFACE_CLASSIFIER_MODELS,
	"openrouter": OPENROUTER_CLASSIFIER_MODELS,
};
