// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import { ANTHROPIC_MODELS } from "./providers/anthropic.models.ts";
import { HUGGINGFACE_MODELS } from "./providers/huggingface.models.ts";
import { OPENROUTER_MODELS } from "./providers/openrouter.models.ts";

export const MODELS: {
	readonly "anthropic": typeof ANTHROPIC_MODELS;
	readonly "huggingface": typeof HUGGINGFACE_MODELS;
	readonly "openrouter": typeof OPENROUTER_MODELS;
} = {
	"anthropic": ANTHROPIC_MODELS,
	"huggingface": HUGGINGFACE_MODELS,
	"openrouter": OPENROUTER_MODELS,
};
